// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos.proto

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DepthOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Depth)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string exchange = 1;</code>
     */
    java.lang.String getExchange();
    /**
     * <code>string exchange = 1;</code>
     */
    com.google.protobuf.ByteString
        getExchangeBytes();

    /**
     * <code>string base = 2;</code>
     */
    java.lang.String getBase();
    /**
     * <code>string base = 2;</code>
     */
    com.google.protobuf.ByteString
        getBaseBytes();

    /**
     * <code>string quote = 3;</code>
     */
    java.lang.String getQuote();
    /**
     * <code>string quote = 3;</code>
     */
    com.google.protobuf.ByteString
        getQuoteBytes();

    /**
     * <code>repeated .Depth.BidAsk bids = 4;</code>
     */
    java.util.List<Protos.Depth.BidAsk> 
        getBidsList();
    /**
     * <code>repeated .Depth.BidAsk bids = 4;</code>
     */
    Protos.Depth.BidAsk getBids(int index);
    /**
     * <code>repeated .Depth.BidAsk bids = 4;</code>
     */
    int getBidsCount();
    /**
     * <code>repeated .Depth.BidAsk bids = 4;</code>
     */
    java.util.List<? extends Protos.Depth.BidAskOrBuilder> 
        getBidsOrBuilderList();
    /**
     * <code>repeated .Depth.BidAsk bids = 4;</code>
     */
    Protos.Depth.BidAskOrBuilder getBidsOrBuilder(
        int index);

    /**
     * <code>repeated .Depth.BidAsk asks = 5;</code>
     */
    java.util.List<Protos.Depth.BidAsk> 
        getAsksList();
    /**
     * <code>repeated .Depth.BidAsk asks = 5;</code>
     */
    Protos.Depth.BidAsk getAsks(int index);
    /**
     * <code>repeated .Depth.BidAsk asks = 5;</code>
     */
    int getAsksCount();
    /**
     * <code>repeated .Depth.BidAsk asks = 5;</code>
     */
    java.util.List<? extends Protos.Depth.BidAskOrBuilder> 
        getAsksOrBuilderList();
    /**
     * <code>repeated .Depth.BidAsk asks = 5;</code>
     */
    Protos.Depth.BidAskOrBuilder getAsksOrBuilder(
        int index);

    /**
     * <code>int64 timestamp = 6;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code Depth}
   */
  public  static final class Depth extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Depth)
      DepthOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Depth.newBuilder() to construct.
    private Depth(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Depth() {
      exchange_ = "";
      base_ = "";
      quote_ = "";
      bids_ = java.util.Collections.emptyList();
      asks_ = java.util.Collections.emptyList();
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Depth(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              exchange_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              base_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              quote_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                bids_ = new java.util.ArrayList<Protos.Depth.BidAsk>();
                mutable_bitField0_ |= 0x00000008;
              }
              bids_.add(
                  input.readMessage(Protos.Depth.BidAsk.parser(), extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                asks_ = new java.util.ArrayList<Protos.Depth.BidAsk>();
                mutable_bitField0_ |= 0x00000010;
              }
              asks_.add(
                  input.readMessage(Protos.Depth.BidAsk.parser(), extensionRegistry));
              break;
            }
            case 48: {

              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          bids_ = java.util.Collections.unmodifiableList(bids_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          asks_ = java.util.Collections.unmodifiableList(asks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protos.internal_static_Depth_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protos.internal_static_Depth_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protos.Depth.class, Protos.Depth.Builder.class);
    }

    public interface BidAskOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Depth.BidAsk)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>double price = 1;</code>
       */
      double getPrice();

      /**
       * <code>double amount = 2;</code>
       */
      double getAmount();
    }
    /**
     * Protobuf type {@code Depth.BidAsk}
     */
    public  static final class BidAsk extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Depth.BidAsk)
        BidAskOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use BidAsk.newBuilder() to construct.
      private BidAsk(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private BidAsk() {
        price_ = 0D;
        amount_ = 0D;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private BidAsk(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 9: {

                price_ = input.readDouble();
                break;
              }
              case 17: {

                amount_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protos.internal_static_Depth_BidAsk_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protos.internal_static_Depth_BidAsk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protos.Depth.BidAsk.class, Protos.Depth.BidAsk.Builder.class);
      }

      public static final int PRICE_FIELD_NUMBER = 1;
      private double price_;
      /**
       * <code>double price = 1;</code>
       */
      public double getPrice() {
        return price_;
      }

      public static final int AMOUNT_FIELD_NUMBER = 2;
      private double amount_;
      /**
       * <code>double amount = 2;</code>
       */
      public double getAmount() {
        return amount_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (price_ != 0D) {
          output.writeDouble(1, price_);
        }
        if (amount_ != 0D) {
          output.writeDouble(2, amount_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (price_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, price_);
        }
        if (amount_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, amount_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Protos.Depth.BidAsk)) {
          return super.equals(obj);
        }
        Protos.Depth.BidAsk other = (Protos.Depth.BidAsk) obj;

        boolean result = true;
        result = result && (
            java.lang.Double.doubleToLongBits(getPrice())
            == java.lang.Double.doubleToLongBits(
                other.getPrice()));
        result = result && (
            java.lang.Double.doubleToLongBits(getAmount())
            == java.lang.Double.doubleToLongBits(
                other.getAmount()));
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getPrice()));
        hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getAmount()));
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Protos.Depth.BidAsk parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Protos.Depth.BidAsk parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Protos.Depth.BidAsk parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Protos.Depth.BidAsk parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Protos.Depth.BidAsk parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Protos.Depth.BidAsk parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Protos.Depth.BidAsk parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Protos.Depth.BidAsk parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Protos.Depth.BidAsk parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Protos.Depth.BidAsk parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Protos.Depth.BidAsk parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Protos.Depth.BidAsk parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Protos.Depth.BidAsk prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Depth.BidAsk}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Depth.BidAsk)
          Protos.Depth.BidAskOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Protos.internal_static_Depth_BidAsk_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Protos.internal_static_Depth_BidAsk_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Protos.Depth.BidAsk.class, Protos.Depth.BidAsk.Builder.class);
        }

        // Construct using Protos.Depth.BidAsk.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          price_ = 0D;

          amount_ = 0D;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Protos.internal_static_Depth_BidAsk_descriptor;
        }

        public Protos.Depth.BidAsk getDefaultInstanceForType() {
          return Protos.Depth.BidAsk.getDefaultInstance();
        }

        public Protos.Depth.BidAsk build() {
          Protos.Depth.BidAsk result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Protos.Depth.BidAsk buildPartial() {
          Protos.Depth.BidAsk result = new Protos.Depth.BidAsk(this);
          result.price_ = price_;
          result.amount_ = amount_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Protos.Depth.BidAsk) {
            return mergeFrom((Protos.Depth.BidAsk)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Protos.Depth.BidAsk other) {
          if (other == Protos.Depth.BidAsk.getDefaultInstance()) return this;
          if (other.getPrice() != 0D) {
            setPrice(other.getPrice());
          }
          if (other.getAmount() != 0D) {
            setAmount(other.getAmount());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Protos.Depth.BidAsk parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Protos.Depth.BidAsk) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private double price_ ;
        /**
         * <code>double price = 1;</code>
         */
        public double getPrice() {
          return price_;
        }
        /**
         * <code>double price = 1;</code>
         */
        public Builder setPrice(double value) {
          
          price_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double price = 1;</code>
         */
        public Builder clearPrice() {
          
          price_ = 0D;
          onChanged();
          return this;
        }

        private double amount_ ;
        /**
         * <code>double amount = 2;</code>
         */
        public double getAmount() {
          return amount_;
        }
        /**
         * <code>double amount = 2;</code>
         */
        public Builder setAmount(double value) {
          
          amount_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double amount = 2;</code>
         */
        public Builder clearAmount() {
          
          amount_ = 0D;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Depth.BidAsk)
      }

      // @@protoc_insertion_point(class_scope:Depth.BidAsk)
      private static final Protos.Depth.BidAsk DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Protos.Depth.BidAsk();
      }

      public static Protos.Depth.BidAsk getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<BidAsk>
          PARSER = new com.google.protobuf.AbstractParser<BidAsk>() {
        public BidAsk parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new BidAsk(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<BidAsk> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<BidAsk> getParserForType() {
        return PARSER;
      }

      public Protos.Depth.BidAsk getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int EXCHANGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object exchange_;
    /**
     * <code>string exchange = 1;</code>
     */
    public java.lang.String getExchange() {
      java.lang.Object ref = exchange_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exchange_ = s;
        return s;
      }
    }
    /**
     * <code>string exchange = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExchangeBytes() {
      java.lang.Object ref = exchange_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASE_FIELD_NUMBER = 2;
    private volatile java.lang.Object base_;
    /**
     * <code>string base = 2;</code>
     */
    public java.lang.String getBase() {
      java.lang.Object ref = base_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        base_ = s;
        return s;
      }
    }
    /**
     * <code>string base = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBaseBytes() {
      java.lang.Object ref = base_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        base_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUOTE_FIELD_NUMBER = 3;
    private volatile java.lang.Object quote_;
    /**
     * <code>string quote = 3;</code>
     */
    public java.lang.String getQuote() {
      java.lang.Object ref = quote_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quote_ = s;
        return s;
      }
    }
    /**
     * <code>string quote = 3;</code>
     */
    public com.google.protobuf.ByteString
        getQuoteBytes() {
      java.lang.Object ref = quote_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quote_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIDS_FIELD_NUMBER = 4;
    private java.util.List<Protos.Depth.BidAsk> bids_;
    /**
     * <code>repeated .Depth.BidAsk bids = 4;</code>
     */
    public java.util.List<Protos.Depth.BidAsk> getBidsList() {
      return bids_;
    }
    /**
     * <code>repeated .Depth.BidAsk bids = 4;</code>
     */
    public java.util.List<? extends Protos.Depth.BidAskOrBuilder> 
        getBidsOrBuilderList() {
      return bids_;
    }
    /**
     * <code>repeated .Depth.BidAsk bids = 4;</code>
     */
    public int getBidsCount() {
      return bids_.size();
    }
    /**
     * <code>repeated .Depth.BidAsk bids = 4;</code>
     */
    public Protos.Depth.BidAsk getBids(int index) {
      return bids_.get(index);
    }
    /**
     * <code>repeated .Depth.BidAsk bids = 4;</code>
     */
    public Protos.Depth.BidAskOrBuilder getBidsOrBuilder(
        int index) {
      return bids_.get(index);
    }

    public static final int ASKS_FIELD_NUMBER = 5;
    private java.util.List<Protos.Depth.BidAsk> asks_;
    /**
     * <code>repeated .Depth.BidAsk asks = 5;</code>
     */
    public java.util.List<Protos.Depth.BidAsk> getAsksList() {
      return asks_;
    }
    /**
     * <code>repeated .Depth.BidAsk asks = 5;</code>
     */
    public java.util.List<? extends Protos.Depth.BidAskOrBuilder> 
        getAsksOrBuilderList() {
      return asks_;
    }
    /**
     * <code>repeated .Depth.BidAsk asks = 5;</code>
     */
    public int getAsksCount() {
      return asks_.size();
    }
    /**
     * <code>repeated .Depth.BidAsk asks = 5;</code>
     */
    public Protos.Depth.BidAsk getAsks(int index) {
      return asks_.get(index);
    }
    /**
     * <code>repeated .Depth.BidAsk asks = 5;</code>
     */
    public Protos.Depth.BidAskOrBuilder getAsksOrBuilder(
        int index) {
      return asks_.get(index);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 6;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getExchangeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, exchange_);
      }
      if (!getBaseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, base_);
      }
      if (!getQuoteBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, quote_);
      }
      for (int i = 0; i < bids_.size(); i++) {
        output.writeMessage(4, bids_.get(i));
      }
      for (int i = 0; i < asks_.size(); i++) {
        output.writeMessage(5, asks_.get(i));
      }
      if (timestamp_ != 0L) {
        output.writeInt64(6, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getExchangeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, exchange_);
      }
      if (!getBaseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, base_);
      }
      if (!getQuoteBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, quote_);
      }
      for (int i = 0; i < bids_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, bids_.get(i));
      }
      for (int i = 0; i < asks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, asks_.get(i));
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Protos.Depth)) {
        return super.equals(obj);
      }
      Protos.Depth other = (Protos.Depth) obj;

      boolean result = true;
      result = result && getExchange()
          .equals(other.getExchange());
      result = result && getBase()
          .equals(other.getBase());
      result = result && getQuote()
          .equals(other.getQuote());
      result = result && getBidsList()
          .equals(other.getBidsList());
      result = result && getAsksList()
          .equals(other.getAsksList());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXCHANGE_FIELD_NUMBER;
      hash = (53 * hash) + getExchange().hashCode();
      hash = (37 * hash) + BASE_FIELD_NUMBER;
      hash = (53 * hash) + getBase().hashCode();
      hash = (37 * hash) + QUOTE_FIELD_NUMBER;
      hash = (53 * hash) + getQuote().hashCode();
      if (getBidsCount() > 0) {
        hash = (37 * hash) + BIDS_FIELD_NUMBER;
        hash = (53 * hash) + getBidsList().hashCode();
      }
      if (getAsksCount() > 0) {
        hash = (37 * hash) + ASKS_FIELD_NUMBER;
        hash = (53 * hash) + getAsksList().hashCode();
      }
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Protos.Depth parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protos.Depth parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protos.Depth parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protos.Depth parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protos.Depth parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protos.Depth parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protos.Depth parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protos.Depth parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protos.Depth parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Protos.Depth parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protos.Depth parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protos.Depth parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Protos.Depth prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Depth}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Depth)
        Protos.DepthOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protos.internal_static_Depth_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protos.internal_static_Depth_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protos.Depth.class, Protos.Depth.Builder.class);
      }

      // Construct using Protos.Depth.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBidsFieldBuilder();
          getAsksFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        exchange_ = "";

        base_ = "";

        quote_ = "";

        if (bidsBuilder_ == null) {
          bids_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          bidsBuilder_.clear();
        }
        if (asksBuilder_ == null) {
          asks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          asksBuilder_.clear();
        }
        timestamp_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protos.internal_static_Depth_descriptor;
      }

      public Protos.Depth getDefaultInstanceForType() {
        return Protos.Depth.getDefaultInstance();
      }

      public Protos.Depth build() {
        Protos.Depth result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Protos.Depth buildPartial() {
        Protos.Depth result = new Protos.Depth(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.exchange_ = exchange_;
        result.base_ = base_;
        result.quote_ = quote_;
        if (bidsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            bids_ = java.util.Collections.unmodifiableList(bids_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.bids_ = bids_;
        } else {
          result.bids_ = bidsBuilder_.build();
        }
        if (asksBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            asks_ = java.util.Collections.unmodifiableList(asks_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.asks_ = asks_;
        } else {
          result.asks_ = asksBuilder_.build();
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protos.Depth) {
          return mergeFrom((Protos.Depth)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protos.Depth other) {
        if (other == Protos.Depth.getDefaultInstance()) return this;
        if (!other.getExchange().isEmpty()) {
          exchange_ = other.exchange_;
          onChanged();
        }
        if (!other.getBase().isEmpty()) {
          base_ = other.base_;
          onChanged();
        }
        if (!other.getQuote().isEmpty()) {
          quote_ = other.quote_;
          onChanged();
        }
        if (bidsBuilder_ == null) {
          if (!other.bids_.isEmpty()) {
            if (bids_.isEmpty()) {
              bids_ = other.bids_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureBidsIsMutable();
              bids_.addAll(other.bids_);
            }
            onChanged();
          }
        } else {
          if (!other.bids_.isEmpty()) {
            if (bidsBuilder_.isEmpty()) {
              bidsBuilder_.dispose();
              bidsBuilder_ = null;
              bids_ = other.bids_;
              bitField0_ = (bitField0_ & ~0x00000008);
              bidsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBidsFieldBuilder() : null;
            } else {
              bidsBuilder_.addAllMessages(other.bids_);
            }
          }
        }
        if (asksBuilder_ == null) {
          if (!other.asks_.isEmpty()) {
            if (asks_.isEmpty()) {
              asks_ = other.asks_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureAsksIsMutable();
              asks_.addAll(other.asks_);
            }
            onChanged();
          }
        } else {
          if (!other.asks_.isEmpty()) {
            if (asksBuilder_.isEmpty()) {
              asksBuilder_.dispose();
              asksBuilder_ = null;
              asks_ = other.asks_;
              bitField0_ = (bitField0_ & ~0x00000010);
              asksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAsksFieldBuilder() : null;
            } else {
              asksBuilder_.addAllMessages(other.asks_);
            }
          }
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protos.Depth parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protos.Depth) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object exchange_ = "";
      /**
       * <code>string exchange = 1;</code>
       */
      public java.lang.String getExchange() {
        java.lang.Object ref = exchange_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exchange_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exchange = 1;</code>
       */
      public com.google.protobuf.ByteString
          getExchangeBytes() {
        java.lang.Object ref = exchange_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchange_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exchange = 1;</code>
       */
      public Builder setExchange(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exchange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string exchange = 1;</code>
       */
      public Builder clearExchange() {
        
        exchange_ = getDefaultInstance().getExchange();
        onChanged();
        return this;
      }
      /**
       * <code>string exchange = 1;</code>
       */
      public Builder setExchangeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        exchange_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object base_ = "";
      /**
       * <code>string base = 2;</code>
       */
      public java.lang.String getBase() {
        java.lang.Object ref = base_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          base_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string base = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBaseBytes() {
        java.lang.Object ref = base_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          base_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string base = 2;</code>
       */
      public Builder setBase(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        base_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string base = 2;</code>
       */
      public Builder clearBase() {
        
        base_ = getDefaultInstance().getBase();
        onChanged();
        return this;
      }
      /**
       * <code>string base = 2;</code>
       */
      public Builder setBaseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        base_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object quote_ = "";
      /**
       * <code>string quote = 3;</code>
       */
      public java.lang.String getQuote() {
        java.lang.Object ref = quote_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          quote_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string quote = 3;</code>
       */
      public com.google.protobuf.ByteString
          getQuoteBytes() {
        java.lang.Object ref = quote_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          quote_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string quote = 3;</code>
       */
      public Builder setQuote(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        quote_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string quote = 3;</code>
       */
      public Builder clearQuote() {
        
        quote_ = getDefaultInstance().getQuote();
        onChanged();
        return this;
      }
      /**
       * <code>string quote = 3;</code>
       */
      public Builder setQuoteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        quote_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Protos.Depth.BidAsk> bids_ =
        java.util.Collections.emptyList();
      private void ensureBidsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          bids_ = new java.util.ArrayList<Protos.Depth.BidAsk>(bids_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Protos.Depth.BidAsk, Protos.Depth.BidAsk.Builder, Protos.Depth.BidAskOrBuilder> bidsBuilder_;

      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public java.util.List<Protos.Depth.BidAsk> getBidsList() {
        if (bidsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bids_);
        } else {
          return bidsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public int getBidsCount() {
        if (bidsBuilder_ == null) {
          return bids_.size();
        } else {
          return bidsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Protos.Depth.BidAsk getBids(int index) {
        if (bidsBuilder_ == null) {
          return bids_.get(index);
        } else {
          return bidsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Builder setBids(
          int index, Protos.Depth.BidAsk value) {
        if (bidsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBidsIsMutable();
          bids_.set(index, value);
          onChanged();
        } else {
          bidsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Builder setBids(
          int index, Protos.Depth.BidAsk.Builder builderForValue) {
        if (bidsBuilder_ == null) {
          ensureBidsIsMutable();
          bids_.set(index, builderForValue.build());
          onChanged();
        } else {
          bidsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Builder addBids(Protos.Depth.BidAsk value) {
        if (bidsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBidsIsMutable();
          bids_.add(value);
          onChanged();
        } else {
          bidsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Builder addBids(
          int index, Protos.Depth.BidAsk value) {
        if (bidsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBidsIsMutable();
          bids_.add(index, value);
          onChanged();
        } else {
          bidsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Builder addBids(
          Protos.Depth.BidAsk.Builder builderForValue) {
        if (bidsBuilder_ == null) {
          ensureBidsIsMutable();
          bids_.add(builderForValue.build());
          onChanged();
        } else {
          bidsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Builder addBids(
          int index, Protos.Depth.BidAsk.Builder builderForValue) {
        if (bidsBuilder_ == null) {
          ensureBidsIsMutable();
          bids_.add(index, builderForValue.build());
          onChanged();
        } else {
          bidsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Builder addAllBids(
          java.lang.Iterable<? extends Protos.Depth.BidAsk> values) {
        if (bidsBuilder_ == null) {
          ensureBidsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bids_);
          onChanged();
        } else {
          bidsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Builder clearBids() {
        if (bidsBuilder_ == null) {
          bids_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          bidsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Builder removeBids(int index) {
        if (bidsBuilder_ == null) {
          ensureBidsIsMutable();
          bids_.remove(index);
          onChanged();
        } else {
          bidsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Protos.Depth.BidAsk.Builder getBidsBuilder(
          int index) {
        return getBidsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Protos.Depth.BidAskOrBuilder getBidsOrBuilder(
          int index) {
        if (bidsBuilder_ == null) {
          return bids_.get(index);  } else {
          return bidsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public java.util.List<? extends Protos.Depth.BidAskOrBuilder> 
           getBidsOrBuilderList() {
        if (bidsBuilder_ != null) {
          return bidsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bids_);
        }
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Protos.Depth.BidAsk.Builder addBidsBuilder() {
        return getBidsFieldBuilder().addBuilder(
            Protos.Depth.BidAsk.getDefaultInstance());
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public Protos.Depth.BidAsk.Builder addBidsBuilder(
          int index) {
        return getBidsFieldBuilder().addBuilder(
            index, Protos.Depth.BidAsk.getDefaultInstance());
      }
      /**
       * <code>repeated .Depth.BidAsk bids = 4;</code>
       */
      public java.util.List<Protos.Depth.BidAsk.Builder> 
           getBidsBuilderList() {
        return getBidsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Protos.Depth.BidAsk, Protos.Depth.BidAsk.Builder, Protos.Depth.BidAskOrBuilder> 
          getBidsFieldBuilder() {
        if (bidsBuilder_ == null) {
          bidsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Protos.Depth.BidAsk, Protos.Depth.BidAsk.Builder, Protos.Depth.BidAskOrBuilder>(
                  bids_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          bids_ = null;
        }
        return bidsBuilder_;
      }

      private java.util.List<Protos.Depth.BidAsk> asks_ =
        java.util.Collections.emptyList();
      private void ensureAsksIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          asks_ = new java.util.ArrayList<Protos.Depth.BidAsk>(asks_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Protos.Depth.BidAsk, Protos.Depth.BidAsk.Builder, Protos.Depth.BidAskOrBuilder> asksBuilder_;

      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public java.util.List<Protos.Depth.BidAsk> getAsksList() {
        if (asksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(asks_);
        } else {
          return asksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public int getAsksCount() {
        if (asksBuilder_ == null) {
          return asks_.size();
        } else {
          return asksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Protos.Depth.BidAsk getAsks(int index) {
        if (asksBuilder_ == null) {
          return asks_.get(index);
        } else {
          return asksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Builder setAsks(
          int index, Protos.Depth.BidAsk value) {
        if (asksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAsksIsMutable();
          asks_.set(index, value);
          onChanged();
        } else {
          asksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Builder setAsks(
          int index, Protos.Depth.BidAsk.Builder builderForValue) {
        if (asksBuilder_ == null) {
          ensureAsksIsMutable();
          asks_.set(index, builderForValue.build());
          onChanged();
        } else {
          asksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Builder addAsks(Protos.Depth.BidAsk value) {
        if (asksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAsksIsMutable();
          asks_.add(value);
          onChanged();
        } else {
          asksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Builder addAsks(
          int index, Protos.Depth.BidAsk value) {
        if (asksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAsksIsMutable();
          asks_.add(index, value);
          onChanged();
        } else {
          asksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Builder addAsks(
          Protos.Depth.BidAsk.Builder builderForValue) {
        if (asksBuilder_ == null) {
          ensureAsksIsMutable();
          asks_.add(builderForValue.build());
          onChanged();
        } else {
          asksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Builder addAsks(
          int index, Protos.Depth.BidAsk.Builder builderForValue) {
        if (asksBuilder_ == null) {
          ensureAsksIsMutable();
          asks_.add(index, builderForValue.build());
          onChanged();
        } else {
          asksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Builder addAllAsks(
          java.lang.Iterable<? extends Protos.Depth.BidAsk> values) {
        if (asksBuilder_ == null) {
          ensureAsksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, asks_);
          onChanged();
        } else {
          asksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Builder clearAsks() {
        if (asksBuilder_ == null) {
          asks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          asksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Builder removeAsks(int index) {
        if (asksBuilder_ == null) {
          ensureAsksIsMutable();
          asks_.remove(index);
          onChanged();
        } else {
          asksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Protos.Depth.BidAsk.Builder getAsksBuilder(
          int index) {
        return getAsksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Protos.Depth.BidAskOrBuilder getAsksOrBuilder(
          int index) {
        if (asksBuilder_ == null) {
          return asks_.get(index);  } else {
          return asksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public java.util.List<? extends Protos.Depth.BidAskOrBuilder> 
           getAsksOrBuilderList() {
        if (asksBuilder_ != null) {
          return asksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(asks_);
        }
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Protos.Depth.BidAsk.Builder addAsksBuilder() {
        return getAsksFieldBuilder().addBuilder(
            Protos.Depth.BidAsk.getDefaultInstance());
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public Protos.Depth.BidAsk.Builder addAsksBuilder(
          int index) {
        return getAsksFieldBuilder().addBuilder(
            index, Protos.Depth.BidAsk.getDefaultInstance());
      }
      /**
       * <code>repeated .Depth.BidAsk asks = 5;</code>
       */
      public java.util.List<Protos.Depth.BidAsk.Builder> 
           getAsksBuilderList() {
        return getAsksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Protos.Depth.BidAsk, Protos.Depth.BidAsk.Builder, Protos.Depth.BidAskOrBuilder> 
          getAsksFieldBuilder() {
        if (asksBuilder_ == null) {
          asksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Protos.Depth.BidAsk, Protos.Depth.BidAsk.Builder, Protos.Depth.BidAskOrBuilder>(
                  asks_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          asks_ = null;
        }
        return asksBuilder_;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 6;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 6;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 6;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Depth)
    }

    // @@protoc_insertion_point(class_scope:Depth)
    private static final Protos.Depth DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Protos.Depth();
    }

    public static Protos.Depth getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Depth>
        PARSER = new com.google.protobuf.AbstractParser<Depth>() {
      public Depth parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Depth(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Depth> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Depth> getParserForType() {
      return PARSER;
    }

    public Protos.Depth getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Depth_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Depth_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Depth_BidAsk_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Depth_BidAsk_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014protos.proto\"\254\001\n\005Depth\022\020\n\010exchange\030\001 \001" +
      "(\t\022\014\n\004base\030\002 \001(\t\022\r\n\005quote\030\003 \001(\t\022\033\n\004bids\030" +
      "\004 \003(\0132\r.Depth.BidAsk\022\033\n\004asks\030\005 \003(\0132\r.Dep" +
      "th.BidAsk\022\021\n\ttimestamp\030\006 \001(\003\032\'\n\006BidAsk\022\r" +
      "\n\005price\030\001 \001(\001\022\016\n\006amount\030\002 \001(\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Depth_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Depth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Depth_descriptor,
        new java.lang.String[] { "Exchange", "Base", "Quote", "Bids", "Asks", "Timestamp", });
    internal_static_Depth_BidAsk_descriptor =
      internal_static_Depth_descriptor.getNestedTypes().get(0);
    internal_static_Depth_BidAsk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Depth_BidAsk_descriptor,
        new java.lang.String[] { "Price", "Amount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
