// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package sansigmabuffers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderPanel_OrderSide int32

const (
	OrderPanel_Buy  OrderPanel_OrderSide = 0
	OrderPanel_Sell OrderPanel_OrderSide = 1
)

var OrderPanel_OrderSide_name = map[int32]string{
	0: "Buy",
	1: "Sell",
}

var OrderPanel_OrderSide_value = map[string]int32{
	"Buy":  0,
	"Sell": 1,
}

func (x OrderPanel_OrderSide) String() string {
	return proto.EnumName(OrderPanel_OrderSide_name, int32(x))
}

func (OrderPanel_OrderSide) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4, 0}
}

type Arbitrage_ArbitrageType int32

const (
	Arbitrage_Simple     Arbitrage_ArbitrageType = 0
	Arbitrage_Triangular Arbitrage_ArbitrageType = 1
	Arbitrage_Circle     Arbitrage_ArbitrageType = 2
)

var Arbitrage_ArbitrageType_name = map[int32]string{
	0: "Simple",
	1: "Triangular",
	2: "Circle",
}

var Arbitrage_ArbitrageType_value = map[string]int32{
	"Simple":     0,
	"Triangular": 1,
	"Circle":     2,
}

func (x Arbitrage_ArbitrageType) String() string {
	return proto.EnumName(Arbitrage_ArbitrageType_name, int32(x))
}

func (Arbitrage_ArbitrageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{5, 0}
}

type BidAskSchema struct {
	Price                float64  `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidAskSchema) Reset()         { *m = BidAskSchema{} }
func (m *BidAskSchema) String() string { return proto.CompactTextString(m) }
func (*BidAskSchema) ProtoMessage()    {}
func (*BidAskSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *BidAskSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidAskSchema.Unmarshal(m, b)
}
func (m *BidAskSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidAskSchema.Marshal(b, m, deterministic)
}
func (m *BidAskSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidAskSchema.Merge(m, src)
}
func (m *BidAskSchema) XXX_Size() int {
	return xxx_messageInfo_BidAskSchema.Size(m)
}
func (m *BidAskSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_BidAskSchema.DiscardUnknown(m)
}

var xxx_messageInfo_BidAskSchema proto.InternalMessageInfo

func (m *BidAskSchema) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BidAskSchema) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type DepthSchema struct {
	Exchange             string          `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Base                 string          `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string          `protobuf:"bytes,3,opt,name=quote,proto3" json:"quote,omitempty"`
	Bids                 []*BidAskSchema `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks                 []*BidAskSchema `protobuf:"bytes,5,rep,name=asks,proto3" json:"asks,omitempty"`
	Timestamp            int64           `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Key                  string          `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DepthSchema) Reset()         { *m = DepthSchema{} }
func (m *DepthSchema) String() string { return proto.CompactTextString(m) }
func (*DepthSchema) ProtoMessage()    {}
func (*DepthSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *DepthSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepthSchema.Unmarshal(m, b)
}
func (m *DepthSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepthSchema.Marshal(b, m, deterministic)
}
func (m *DepthSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepthSchema.Merge(m, src)
}
func (m *DepthSchema) XXX_Size() int {
	return xxx_messageInfo_DepthSchema.Size(m)
}
func (m *DepthSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_DepthSchema.DiscardUnknown(m)
}

var xxx_messageInfo_DepthSchema proto.InternalMessageInfo

func (m *DepthSchema) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *DepthSchema) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *DepthSchema) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *DepthSchema) GetBids() []*BidAskSchema {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *DepthSchema) GetAsks() []*BidAskSchema {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *DepthSchema) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DepthSchema) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type SpreadSchema struct {
	LongExchange         string   `protobuf:"bytes,1,opt,name=long_exchange,json=longExchange,proto3" json:"long_exchange,omitempty"`
	ShortExchange        string   `protobuf:"bytes,2,opt,name=short_exchange,json=shortExchange,proto3" json:"short_exchange,omitempty"`
	Base                 string   `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string   `protobuf:"bytes,4,opt,name=quote,proto3" json:"quote,omitempty"`
	ProfitRate           float64  `protobuf:"fixed64,5,opt,name=profit_rate,json=profitRate,proto3" json:"profit_rate,omitempty"`
	Profit               float64  `protobuf:"fixed64,6,opt,name=profit,proto3" json:"profit,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	InvestedCapital      float64  `protobuf:"fixed64,8,opt,name=invested_capital,json=investedCapital,proto3" json:"invested_capital,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpreadSchema) Reset()         { *m = SpreadSchema{} }
func (m *SpreadSchema) String() string { return proto.CompactTextString(m) }
func (*SpreadSchema) ProtoMessage()    {}
func (*SpreadSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *SpreadSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpreadSchema.Unmarshal(m, b)
}
func (m *SpreadSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpreadSchema.Marshal(b, m, deterministic)
}
func (m *SpreadSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpreadSchema.Merge(m, src)
}
func (m *SpreadSchema) XXX_Size() int {
	return xxx_messageInfo_SpreadSchema.Size(m)
}
func (m *SpreadSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_SpreadSchema.DiscardUnknown(m)
}

var xxx_messageInfo_SpreadSchema proto.InternalMessageInfo

func (m *SpreadSchema) GetLongExchange() string {
	if m != nil {
		return m.LongExchange
	}
	return ""
}

func (m *SpreadSchema) GetShortExchange() string {
	if m != nil {
		return m.ShortExchange
	}
	return ""
}

func (m *SpreadSchema) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *SpreadSchema) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *SpreadSchema) GetProfitRate() float64 {
	if m != nil {
		return m.ProfitRate
	}
	return 0
}

func (m *SpreadSchema) GetProfit() float64 {
	if m != nil {
		return m.Profit
	}
	return 0
}

func (m *SpreadSchema) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SpreadSchema) GetInvestedCapital() float64 {
	if m != nil {
		return m.InvestedCapital
	}
	return 0
}

type TradeSchema struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TradeId              string   `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Exchange             string   `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Base                 string   `protobuf:"bytes,4,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string   `protobuf:"bytes,5,opt,name=quote,proto3" json:"quote,omitempty"`
	Price                float64  `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Amount               float64  `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp            int64    `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Side                 string   `protobuf:"bytes,9,opt,name=side,proto3" json:"side,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeSchema) Reset()         { *m = TradeSchema{} }
func (m *TradeSchema) String() string { return proto.CompactTextString(m) }
func (*TradeSchema) ProtoMessage()    {}
func (*TradeSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *TradeSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeSchema.Unmarshal(m, b)
}
func (m *TradeSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeSchema.Marshal(b, m, deterministic)
}
func (m *TradeSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeSchema.Merge(m, src)
}
func (m *TradeSchema) XXX_Size() int {
	return xxx_messageInfo_TradeSchema.Size(m)
}
func (m *TradeSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeSchema.DiscardUnknown(m)
}

var xxx_messageInfo_TradeSchema proto.InternalMessageInfo

func (m *TradeSchema) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TradeSchema) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

func (m *TradeSchema) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *TradeSchema) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *TradeSchema) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *TradeSchema) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TradeSchema) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TradeSchema) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TradeSchema) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

type OrderPanel struct {
	Exchange             string               `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Base                 string               `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string               `protobuf:"bytes,3,opt,name=quote,proto3" json:"quote,omitempty"`
	Side                 OrderPanel_OrderSide `protobuf:"varint,4,opt,name=side,proto3,enum=sansigmabuffers.OrderPanel_OrderSide" json:"side,omitempty"`
	Price                float64              `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	DepthAmount          float64              `protobuf:"fixed64,6,opt,name=depth_amount,json=depthAmount,proto3" json:"depth_amount,omitempty"`
	OrderAmount          float64              `protobuf:"fixed64,7,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderPanel) Reset()         { *m = OrderPanel{} }
func (m *OrderPanel) String() string { return proto.CompactTextString(m) }
func (*OrderPanel) ProtoMessage()    {}
func (*OrderPanel) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}

func (m *OrderPanel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderPanel.Unmarshal(m, b)
}
func (m *OrderPanel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderPanel.Marshal(b, m, deterministic)
}
func (m *OrderPanel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderPanel.Merge(m, src)
}
func (m *OrderPanel) XXX_Size() int {
	return xxx_messageInfo_OrderPanel.Size(m)
}
func (m *OrderPanel) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderPanel.DiscardUnknown(m)
}

var xxx_messageInfo_OrderPanel proto.InternalMessageInfo

func (m *OrderPanel) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *OrderPanel) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *OrderPanel) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *OrderPanel) GetSide() OrderPanel_OrderSide {
	if m != nil {
		return m.Side
	}
	return OrderPanel_Buy
}

func (m *OrderPanel) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderPanel) GetDepthAmount() float64 {
	if m != nil {
		return m.DepthAmount
	}
	return 0
}

func (m *OrderPanel) GetOrderAmount() float64 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

type Arbitrage struct {
	Type                 Arbitrage_ArbitrageType `protobuf:"varint,1,opt,name=type,proto3,enum=sansigmabuffers.Arbitrage_ArbitrageType" json:"type,omitempty"`
	Orders               []*OrderPanel           `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	Profit               float64                 `protobuf:"fixed64,3,opt,name=profit,proto3" json:"profit,omitempty"`
	ProfitRate           float64                 `protobuf:"fixed64,4,opt,name=profit_rate,json=profitRate,proto3" json:"profit_rate,omitempty"`
	Investment           float64                 `protobuf:"fixed64,5,opt,name=investment,proto3" json:"investment,omitempty"`
	ProfitAsset          string                  `protobuf:"bytes,6,opt,name=profit_asset,json=profitAsset,proto3" json:"profit_asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Arbitrage) Reset()         { *m = Arbitrage{} }
func (m *Arbitrage) String() string { return proto.CompactTextString(m) }
func (*Arbitrage) ProtoMessage()    {}
func (*Arbitrage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{5}
}

func (m *Arbitrage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Arbitrage.Unmarshal(m, b)
}
func (m *Arbitrage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Arbitrage.Marshal(b, m, deterministic)
}
func (m *Arbitrage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Arbitrage.Merge(m, src)
}
func (m *Arbitrage) XXX_Size() int {
	return xxx_messageInfo_Arbitrage.Size(m)
}
func (m *Arbitrage) XXX_DiscardUnknown() {
	xxx_messageInfo_Arbitrage.DiscardUnknown(m)
}

var xxx_messageInfo_Arbitrage proto.InternalMessageInfo

func (m *Arbitrage) GetType() Arbitrage_ArbitrageType {
	if m != nil {
		return m.Type
	}
	return Arbitrage_Simple
}

func (m *Arbitrage) GetOrders() []*OrderPanel {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *Arbitrage) GetProfit() float64 {
	if m != nil {
		return m.Profit
	}
	return 0
}

func (m *Arbitrage) GetProfitRate() float64 {
	if m != nil {
		return m.ProfitRate
	}
	return 0
}

func (m *Arbitrage) GetInvestment() float64 {
	if m != nil {
		return m.Investment
	}
	return 0
}

func (m *Arbitrage) GetProfitAsset() string {
	if m != nil {
		return m.ProfitAsset
	}
	return ""
}

func init() {
	proto.RegisterEnum("sansigmabuffers.OrderPanel_OrderSide", OrderPanel_OrderSide_name, OrderPanel_OrderSide_value)
	proto.RegisterEnum("sansigmabuffers.Arbitrage_ArbitrageType", Arbitrage_ArbitrageType_name, Arbitrage_ArbitrageType_value)
	proto.RegisterType((*BidAskSchema)(nil), "sansigmabuffers.BidAskSchema")
	proto.RegisterType((*DepthSchema)(nil), "sansigmabuffers.DepthSchema")
	proto.RegisterType((*SpreadSchema)(nil), "sansigmabuffers.SpreadSchema")
	proto.RegisterType((*TradeSchema)(nil), "sansigmabuffers.TradeSchema")
	proto.RegisterType((*OrderPanel)(nil), "sansigmabuffers.OrderPanel")
	proto.RegisterType((*Arbitrage)(nil), "sansigmabuffers.Arbitrage")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xad, 0x63, 0xe7, 0xe1, 0x9b, 0x34, 0xb5, 0x46, 0x08, 0x99, 0x57, 0x69, 0x8d, 0x2a, 0x85,
	0x4d, 0x25, 0xda, 0x05, 0x42, 0xea, 0x26, 0x2d, 0x5d, 0xb0, 0x02, 0x39, 0xdd, 0x47, 0x93, 0xf8,
	0x36, 0x19, 0xd5, 0x2f, 0x66, 0x26, 0x88, 0xfc, 0x00, 0x12, 0xdf, 0xc3, 0x0f, 0xb1, 0xe5, 0x2f,
	0xd0, 0x3c, 0x9a, 0xd8, 0x6e, 0x40, 0x2c, 0xd8, 0xdd, 0x7b, 0x72, 0x1f, 0x73, 0x8e, 0xcf, 0x0d,
	0x0c, 0xc4, 0x7c, 0x89, 0x19, 0x3d, 0x2d, 0x79, 0x21, 0x0b, 0x72, 0x20, 0x68, 0x2e, 0xd8, 0x22,
	0xa3, 0xb3, 0xd5, 0xed, 0x2d, 0x72, 0x11, 0x5d, 0xc0, 0xe0, 0x92, 0x25, 0x63, 0x71, 0x37, 0xd1,
	0x65, 0xe4, 0x11, 0xb4, 0x4b, 0xce, 0xe6, 0x18, 0x3a, 0x47, 0xce, 0xc8, 0x89, 0x4d, 0x42, 0x1e,
	0x43, 0x87, 0x66, 0xc5, 0x2a, 0x97, 0x61, 0x4b, 0xc3, 0x36, 0x8b, 0x7e, 0x39, 0xd0, 0x7f, 0x8f,
	0xa5, 0x5c, 0xda, 0xee, 0xa7, 0xd0, 0xc3, 0xaf, 0xf3, 0x25, 0xcd, 0x17, 0x66, 0x80, 0x1f, 0x6f,
	0x72, 0x42, 0xc0, 0x9b, 0x51, 0x81, 0x7a, 0x82, 0x1f, 0xeb, 0x58, 0x6d, 0xfb, 0xbc, 0x2a, 0x24,
	0x86, 0xae, 0x06, 0x4d, 0x42, 0xde, 0x80, 0x37, 0x63, 0x89, 0x08, 0xbd, 0x23, 0x77, 0xd4, 0x3f,
	0x7b, 0x71, 0xda, 0x78, 0xf3, 0x69, 0xf5, 0xc1, 0xb1, 0x2e, 0x55, 0x2d, 0x54, 0xdc, 0x89, 0xb0,
	0xfd, 0x4f, 0x2d, 0xaa, 0x94, 0x3c, 0x07, 0x5f, 0xb2, 0x0c, 0x85, 0xa4, 0x59, 0x19, 0x76, 0x8e,
	0x9c, 0x91, 0x1b, 0x6f, 0x01, 0x12, 0x80, 0x7b, 0x87, 0xeb, 0xb0, 0xab, 0xdf, 0xa5, 0xc2, 0xe8,
	0x5b, 0x0b, 0x06, 0x93, 0x92, 0x23, 0x4d, 0x2c, 0xd9, 0x57, 0xb0, 0x9f, 0x16, 0xf9, 0x62, 0xda,
	0x60, 0x3c, 0x50, 0xe0, 0xf5, 0x3d, 0xeb, 0x13, 0x18, 0x8a, 0x65, 0xc1, 0xe5, 0xb6, 0xca, 0xf0,
	0xdf, 0xd7, 0xe8, 0x75, 0x53, 0x1c, 0x77, 0x97, 0x38, 0x5e, 0x55, 0x9c, 0x97, 0xd0, 0x2f, 0x79,
	0x71, 0xcb, 0xe4, 0x94, 0x53, 0x89, 0x61, 0x5b, 0x7f, 0x0f, 0x30, 0x50, 0x4c, 0xa5, 0xfe, 0x56,
	0x26, 0xd3, 0xa4, 0x9c, 0xd8, 0x66, 0x75, 0xbe, 0xdd, 0x26, 0xdf, 0xd7, 0x10, 0xb0, 0xfc, 0x0b,
	0x0a, 0x89, 0xc9, 0x74, 0x4e, 0x4b, 0x26, 0x69, 0x1a, 0xf6, 0x74, 0xff, 0xc1, 0x3d, 0x7e, 0x65,
	0xe0, 0xe8, 0xa7, 0x03, 0xfd, 0x1b, 0x4e, 0x13, 0xb4, 0x3a, 0x58, 0xa9, 0x9c, 0x8d, 0x54, 0xe4,
	0x09, 0xf4, 0xa4, 0x2a, 0x98, 0xb2, 0xc4, 0xd2, 0xed, 0xea, 0xfc, 0x43, 0x52, 0x73, 0x88, 0xfb,
	0x07, 0x87, 0x78, 0xbb, 0x44, 0x68, 0x57, 0x45, 0xd8, 0xb8, 0xb4, 0xb3, 0xdb, 0xa5, 0xdd, 0xaa,
	0x4b, 0xeb, 0xcc, 0x7b, 0x4d, 0xe6, 0x04, 0x3c, 0xc1, 0x12, 0x0c, 0x7d, 0xb3, 0x55, 0xc5, 0xd1,
	0xf7, 0x16, 0xc0, 0x47, 0x9e, 0x20, 0xff, 0x44, 0x73, 0x4c, 0xff, 0x93, 0xad, 0xdf, 0xd9, 0x45,
	0x8a, 0xde, 0xf0, 0xec, 0xe4, 0x81, 0x47, 0xb7, 0x0b, 0x4d, 0x38, 0x61, 0x09, 0x9a, 0xf7, 0x6c,
	0xf9, 0xb6, 0xab, 0x7c, 0x8f, 0x61, 0x90, 0xa8, 0xe3, 0x9b, 0x5a, 0xd6, 0x46, 0x8c, 0xbe, 0xc6,
	0xc6, 0x86, 0xfa, 0x31, 0x0c, 0x0a, 0x35, 0x6b, 0x5a, 0x13, 0xa6, 0xaf, 0x31, 0x53, 0x12, 0x1d,
	0x82, 0xbf, 0x59, 0x47, 0xba, 0xe0, 0x5e, 0xae, 0xd6, 0xc1, 0x1e, 0xe9, 0x81, 0x37, 0xc1, 0x34,
	0x0d, 0x9c, 0xe8, 0x47, 0x0b, 0xfc, 0x31, 0x9f, 0x31, 0xc9, 0xe9, 0x02, 0xc9, 0x05, 0x78, 0x72,
	0x5d, 0x1a, 0x19, 0x86, 0x67, 0xa3, 0x07, 0x24, 0x36, 0x95, 0xdb, 0xe8, 0x66, 0x5d, 0x62, 0xac,
	0xbb, 0xc8, 0x39, 0x74, 0xf4, 0x6a, 0x11, 0xb6, 0xf4, 0xa1, 0x3e, 0xfb, 0x8b, 0x08, 0xb1, 0x2d,
	0xad, 0x18, 0xda, 0xad, 0x19, 0xba, 0x71, 0x09, 0xde, 0x83, 0x4b, 0x38, 0x04, 0x30, 0xde, 0xcd,
	0x30, 0x97, 0xf7, 0x97, 0xb2, 0x45, 0x94, 0x38, 0x76, 0x00, 0x15, 0x02, 0x8d, 0x7e, 0x7e, 0x6c,
	0x87, 0x8e, 0x15, 0x14, 0xbd, 0x85, 0xfd, 0x1a, 0x0f, 0x02, 0xd0, 0x99, 0xb0, 0xac, 0x4c, 0x31,
	0xd8, 0x23, 0x43, 0x80, 0x1b, 0xce, 0x68, 0xbe, 0x58, 0xa5, 0x94, 0x07, 0x8e, 0xfa, 0xed, 0x8a,
	0xf1, 0x79, 0x8a, 0x41, 0x6b, 0xd6, 0xd1, 0xff, 0xb7, 0xe7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x03, 0xaf, 0xb1, 0xd6, 0x7f, 0x05, 0x00, 0x00,
}
